### ISSUE TITLE
Wrong HP winner

### ISSUE THREAD

**Issue by DarkShoot06** [Mn0ky/QOL-Mod#1]
Hi, with friends we encounter some time (Not lot's of time), the hp of the winner is not the same at the end.
I think it could happen when the person hit lava or thruster or i don't know how .
https://puu.sh/IQUhR.png when blue hit the lava 3 secs ago before the ending.
https://puu.sh/IQUhV.png when i receive thruster and still have them on me after the ending.

Version of the Mod : v1.0.13.1

**Comment by Mn0ky** [comment]
Hello, this is most likely an issue with the game and the way health is calculated. On that note, this issue will be closed.
