### ISSUE TITLE
Mirror portal + show hitboxes

### ISSUE THREAD

**Issue by DoktorDreistein** [Mn0ky/QOL-Mod#3]
For some reason show hitboxes + mirror portal causes the ship to die on slopes. Also, with the mirror portal and showing hitboxes you can't see any hitboxes except for the player. (Cataclysm 63%  ship)

https://github.com/user-attachments/assets/e09910de-9060-46f7-ac61-4ca6e4d90981

**Comment by Mn0ky** [comment]
Wrong game/repo.

**Comment by K4kadu** [comment]
yooo activity on the QOL mod repo xD
